spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/safetravels_dev
    username: postgres
    password: postgres

logging:
  level:
    com.safetravels: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
